# -*- coding: utf-8 -*-
"""EX_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VtiVWuxfrNMOy_xAMtq7D7glRfFQA50R
"""

#import libraries

import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

df  = pd.DataFrame({"Waist_cm":[71,89,64,74,87,93,79,81,75,72,70,66,81,78,110], "Weight_kg":[51,66,45,57,64,75,61,62,55,53,48,46,63,60,100]})
                                                                                       
df.shape

df.plot(kind='scatter',x='Waist_cm',y='Weight_kg')

df.plot(kind='box')
plt.show()

df.corr() # co-relation coefficients

#change to dataframe variables
Waist = pd.DataFrame(df['Waist_cm'])
Weight = pd.DataFrame(df['Weight_kg'])

Waist

#Build Linear regression Model
lm = linear_model.LinearRegression()
model = lm.fit(Waist,Weight)

print(model.coef_)
print(model.intercept_)

model.score(Waist, Weight) #Evaluate the model

Waist_new = [97]
Waist_new = pd.DataFrame(Waist_new)
Waist_predicted = model.predict(Waist_new)

X=([67,78,94])
X= pd.DataFrame(X)
Y= model.predict(X)
Y = pd.DataFrame(Y)
df_result = pd.concat([X,Y], axis =1 ,keys=['Waist_new','Weight_Predicted'])

df_result.head()

df.plot(kind="scatter",x='Waist_cm',y="Weight_kg")
#Plotting the regressioni line
plt.plot(Waist,model.predict(Waist),color='red', linewidth=2)
ax = plt.gca()
ax.patch.set_facecolor('black')

#plotting the predict value
plt.scatter(Waist_new, Waist_predicted, color='yellow')
plt.plot(X,Y, color='blue',linewidth=5)
plt.show()